version: v2
global: 
  runner:
    os_image: ubuntu
  variables: 
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    timeout: 7200
    steps:
    - checkout
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y python3 python3-pip && \
        pip3 install telebot flask pymongo aiohttp python-telegram-bot && \
        pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot && \
        pip install telebot pymongo aiohttp psutil pytz && \
        pip install motor && \
        chmod +x dark && \
        echo "Starting dark.py execution" && \
        python3 dark.py
