version: 1

stages:
  - name: Setup and Dependencies
    steps:
      - type: script
        name: Create Virtual Environment
        command: python3 -m venv venv
      - type: script
        name: Activate Virtual Environment and Install Dependencies
        command: |
          source venv/bin/activate
          pip install telebot flask pymongo aiohttp python-telegram-bot pytz
      - type: script
        name: Make `dark` Executable
        command: chmod +x dark
  - name: Run Application
    steps:
      - type: script
        name: Run `dark.py`
        command: |
          source venv/bin/activate
          python3 dark.py
